
var api=api||{};api.core={decodemailto:function(e){var href=e.getAttribute('href');var address=href.replace(/\[at\]/gmi,'@');address=address.replace(/\[dot\]/gmi,'.');if(href!=address){e.setAttribute('href',address);}}};api.$=function(x){if(typeof x=="string"){x=document.getElementById(x);}
return x;};api.getElementsByClassName=function(e,c,t){e=e||document;t=t||"*";var arrRet=[];var els=e.getElementsByTagName(t);var re=new RegExp("\\b"+c+"\\b");for(var i=0;i<els.length;i++){if(re.test(els[i].className)){arrRet.push(els[i]);}}
return arrRet;};api.bh=function(n,a){var o;if(n!="text"){o=document.createElement(n);for(var i in a){if(i=="class"||i=="className"||i=="cl"){o.className=a[i];}else if(i=="innerHTML"||i=="ih"){o.innerHTML=a[i];}else if(i.indexOf("style.")>-1){var iS=i.split(".");o[iS[0]][iS[1]]=a[i];}else if(i=="style"&&typeof a[i]=="object"){for(var y in a[i])o[i][y]=a[i][y];}else{o.setAttribute(i,a[i]);}}}else{o=document.createTextNode(a);}
return o;};api.parseStringToXml=function(s){var xmlDoc=null;try{xmlDoc=new ActiveXObject("Microsoft.XMLDOM");xmlDoc.async="false";xmlDoc.loadXML(s);}catch(errI){try{parser=new DOMParser();xmlDoc=parser.parseFromString(s,"text/xml");}
catch(errII){}}
return xmlDoc;};api.toggleClassName=function(e,oc,rc){if(e.className==oc){e.className=rc;}else if(e.className==rc){e.className=oc;}};api.getLastStreamNode=function(node){var nL=document.getElementsByTagName(node);return nL[nL.length-1];};api.ajax=function(param){for(var i in param){this[i]=param[i];}
var transport=function(){var t=false;if(typeof window.XDomainRequest!=='undefined'&&(typeof window.XMLHttpRequest==='undefined'||!('withCredentials'in new XMLHttpRequest()))){t=new window.XDomainRequest();}else if(typeof window.XMLHttpRequest!=='undefined'){t=new XMLHttpRequest();}else if(window.ActiveXObject){try{t=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{t=new ActiveXObject("Microsoft.XMLHTTP");}catch(E){t=false;}}}
return t;};var $=function(e){if(typeof e=='string'){e=document.getElementById(e);return e;}};if(!this.method){this.method='GET';}
if(!this.args){this.args=null;}
if(typeof this.async!="boolean"){this.async=true;}
if(!!this.update){var e=$(this.update);this.onsuccess=function(r){e.innerHTML=r.responseText;};}
this.xh=new transport();};api.ajax.prototype.send=function(){var x=this.xh;var f=this.onsuccess;var e=this.onfailure;var a=this.args;x.open(this.method,this.url,this.async);if(this.method=='POST'){x.setRequestHeader("Content-type","application/x-www-form-urlencoded");x.setRequestHeader("Content-length",a.length);x.setRequestHeader("Connection","close");}
if(this.async){var callback_called=false;x.onload=function(){if(!callback_called){callback_called=true;if(typeof x.responseXML==='undefined'){if(window.DOMParser){var parser=new window.DOMParser();x.responseXML=parser.parseFromString(x.responseText,"text/xml")}else{x.responseXML=new ActiveXObject("Microsoft.XMLDOM");x.responseXML.async=false;x.responseXML.loadXML(x.responseText);}}
f(x);}};x.onerror=function(){if(!!e)e(x);};x.onreadystatechange=function(){if(x.readyState==4){if(x.status==200&&!callback_called){callback_called=true;f(x);}
else if(!!e)e(x);}};}
x.send(a);if(!this.async){this.response=x;}};api.ajax.prototype.start=function(x){this.send();var t=this;var executer=function(t){t.send();};this.timer=setInterval(function(){executer(t);},x*1000);};api.ajax.prototype.stop=function(){if(!this.timer){return;}
clearInterval(this.timer);this.timer=null;};if(!this.JSON){this.JSON={};}
(function(){function f(n){return n<10?'0'+n:n;}
if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+
f(this.getUTCMonth()+1)+'-'+
f(this.getUTCDate())+'T'+
f(this.getUTCHours())+':'+
f(this.getUTCMinutes())+':'+
f(this.getUTCSeconds())+'Z':null;};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf();};}
var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
if(typeof rep==='function'){value=rep.call(holder,key,value);}
switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
v=partial.length===0?'[]':gap?'[\n'+gap+
partial.join(',\n'+gap)+'\n'+
mind+']':'['+partial.join(',')+']';gap=mind;return v;}
if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){k=rep[i];if(typeof k==='string'){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+
mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
if(typeof JSON.stringify!=='function'){JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
return str('',{'':value});};}
if(typeof JSON.parse!=='function'){JSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==='object'){for(k in value){if(Object.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined){value[k]=v;}else{delete value[k];}}}}
return reviver.call(holder,key,value);}
cx.lastIndex=0;if(cx.test(text)){text=text.replace(cx,function(a){return'\\u'+
('0000'+a.charCodeAt(0).toString(16)).slice(-4);});}
if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,'@').replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']').replace(/(?:^|:|,)(?:\s*\[)+/g,''))){j=eval('('+text+')');return typeof reviver==='function'?walk({'':j},''):j;}
throw new SyntaxError('JSON.parse');};}}());api.cookie={set:function(name,value,expires,path,domain,secure){var fDate=new Date();var exDate=fDate.getTime();exDate+=1000*3600*24*expires;fDate.setTime(exDate);name+="="+escape(value)+((expires)?"; expires="+fDate.toGMTString():"");name+=((path)?"; path="+path:"");name+=((domain)?"; domain="+domain:"");name+=((secure)?"; secure":"");document.cookie=name;},get:function(name){var dc=document.cookie;if(dc===""){return false;}
var prefix=name+"=";var begin=dc.indexOf("; "+prefix);if(begin==-1){begin=dc.indexOf(prefix);if(begin!==0){return null;}}else{begin+=2;}
var end=document.cookie.indexOf(";",begin);if(end==-1){end=dc.length;}
return(unescape(dc.substring(begin+prefix.length,end))||"");},del:function(name,path,domain){var cookie=name+"="+((path)?";path="+path:"");cookie+=((domain)?";domain="+domain:"");cookie+=";expires=Thu, 01-Jan-1970 00:00:01 GMT";if(this.get(name)){document.cookie=cookie;}},isOn:function(){this.set("apiCookiesOnCheck","true",365);return(this.get("apiCookiesOnCheck")=="true");}};api.imageForSale=function(p){var self=this;for(var i in p)this[i]=p[i];this.imageJson={id:this.id,url:this.url,title:this.title,btnTitle:this.euroFotoBtnTitle,btnTxt:this.euroFotoBtnText,btnDesc:this.euroFotoBtnDesc,backUrl:document.location.toString(),shop:this.photopartner,fotoByline:this.euroFotoByline};this.element.onclick=function(){self.showLightbox()};api.imagesForSale.push(this);}
api.imagesForSale=[];api.imageForSale.prototype={showLightbox:function(){var self=this;$.colorbox({html:$("<div/>").prepend($("<div/>",{className:"euroFotoThumbnail"}).prepend($("<img/>",{src:this.thumbnail.url,css:{width:this.thumbnail.width+"px",height:this.thumbnail.height+"px"}})),$("<h1/>",{html:"Bestill bildeprodukter"}),$("<p/>",{html:this.imageJson.btnDesc}),$("<div/>",{html:this.imageJson.btnTitle,className:"apiOrderImageBtn tostore"}).bind("click",function(){self.buyImage()})),width:"600px",scrolling:false})},buyImage:function()
{$.ajax({url:"/ajax/eurofoto/buyimage.json",type:"POST",data:{"imageJson":JSON.stringify(this.imageJson)},dataType:"json",cache:false,async:false,success:function(data)
{document.location=data.url;},error:function(error)
{}});}};api.effects={};api.effects.scale={animTimer:null,currentTarget:null,originalHeight:null,targetHeight:null,time:0,targetDuration:2,setHeight:function(target,newHeight){target.style.height=newHeight+"px;";},startScale:function(target,newHeight){this.time=0;this.currentTarget=document.getElementById(target);this.targetHeight=newHeight;this.originalHeight=Number(this.currentTarget.offsetHeight);this.animTimer=window.setInterval("api.effects.scale.animate()",30);},stopScale:function(){clearInterval(this.animTimer);},animate:function(){this.time+=0.1;if(this.time<this.targetDuration){var difference=this.targetHeight-this.originalHeight;var newHeight=this.easeInOut(this.time,this.originalHeight,difference,this.targetDuration);this.currentTarget.style.height=newHeight+"px";}else{this.currentTarget.style.height=this.targetHeight+"px";this.stopScale();}},easeInOut:function(t,b,c,d){if(t===0){return b;}
if(t==d){return b+c;}
if((t/=d/2)<1){return c/2*Math.pow(2,10*(t-1))+b;}
return c/2*(-Math.pow(2,-10*--t)+2)+b;}};var api=api||{};api.map=api.map||{};(function(){var mapProperties={};add=function add(map){mapProperties[map.mapId]=map;}
api.map.component={load:function load(mapId){dojo.ready(function(){api.map.component.drawMap(mapId);});},drawMap:function drawMap(mapId){dojo.require("esri.map");var initialExtent=new esri.geometry.Extent({"xmin":mapProperties[mapId].bbox.xmin,"ymin":mapProperties[mapId].bbox.ymin,"xmax":mapProperties[mapId].bbox.xmax,"ymax":mapProperties[mapId].bbox.ymax});var map=new esri.Map(mapId,{extent:initialExtent,logo:false});var imageParameters=new esri.layers.ImageParameters();imageParameters.format="png24";var tiledMapServiceLayer=new esri.layers.ArcGISTiledMapServiceLayer(mapProperties[mapId].mapURL,{"opacity":1,"imageParameters":imageParameters});map.addLayer(tiledMapServiceLayer);dojo.connect(map,"onLoad",function(){for(marker in mapProperties[mapId].markers){api.map.component.drawMarker(map,mapProperties[mapId].markers[marker]);}
map.disableScrollWheelZoom();$('#'+mapId+' .staticMap').remove();});},drawMarker:function drawMarker(map,marker){var symbol=new esri.symbol.PictureMarkerSymbol(marker.image,marker.width,marker.height);symbol.setOffset(marker.offsetX,marker.offsetY);var graphic=new esri.Graphic(new esri.geometry.Point(marker.xpos,marker.ypos),symbol);graphic.setAttributes({"TITLE":marker.description});map.graphics.add(graphic);}};api.map.admin={add:add};})();api.sitestat=function(nedstat_site,counterName){var counturl='http://int.sitestat.com/a-pi/'+nedstat_site+'/s?';counturl+=counterName;counturl+='&amp;ns_type=clickout&amp;ns_action=view';counturl+='&amp;ns__t='+(new Date().getTime());var d=document,l=d.location;ns_pixelUrl=counturl;u=counturl+"&ns_c="+((d.characterSet)?d.characterSet:d.defaultCharset)+"&ns_ti="+escape(d.title)+"&ns_jspageurl="+escape(l&&l.href?l.href:d.URL)+"&ns_referrer="+escape(d.referrer);(d.images)?new Image().src=u:d.write('<'+'p><img src="'+u+'" height="1" width="1" alt="*"><'+'/p>');}
api.qbrick_streamsense=function(nedstat_site,counterName,title){var counturl='http://int.sitestat.com/amedia/mainsite/s?name='+encodeURI(title);counturl+='&ns_site=mainsite'+'&ns_type=hidden'+'&ns_action=view'+'&ns__t='+(new Date().getTime())+'&ns_st_ev='+counterName+'&ns_st_pl='+title+'&ns_st_pr='+title+'&ns_st_ep=1'+'&ns_st_mp=Qbrick'+'&ns_st_sv=4.0'+'&ns_st_sp=1'+'&ns_st_sq=1'+'&a_virtual='+nedstat_site;var d=document,l=d.location;ns_pixelUrl=counturl;u=counturl;(d.images)?new Image().src=u:d.write('<'+'p><img src="'+u+'" height="1" width="1" alt="*"><'+'/p>');}
api.form=function(){};api.form.restore=function(){this.formFields=new Array();};api.form.restore.prototype.preAction=function(e){if(!this.formFields[e.name]||this.formFields[e.name]==e.value){this.formFields[e.name]=e.value;e.value='';}};api.form.restore.prototype.postAction=function(e){if(e.value===''){e.value=this.formFields[e.name];}};api.form.validate=function(){};api.form.validate.prototype.email=function(e,c){var emailExp=/^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/;if(e.value.match(emailExp)){api.callback(c(e,true));return true;}else{api.callback(c(e,false));return false;}};api.video=function(vTitle,vFile,vThumb,tagetID,pWidth,pHeight,nedstatSiteId,nedstatParamMap,instreamAdUrl,playerFileName){var vp=new api.video.player();vp.setVideoPlayerWidth(pWidth);vp.getVideoPlayerHeight(pHeight);vp.setPlayer(globalstaticurl+'common/flash/videoplayer/'+playerFileName)
var vf=new api.video.file();vf.setTitle(vTitle);vf.setFile(vFile);vf.setThumb(vThumb);var flashvars={autoplay:"false",debug:"false",playlist:vf.getPlaylist(),instreamAdUrl:instreamAdUrl+new Date().getTime(),reportURL:api.video.createReportURL(nedstatSiteId,nedstatParamMap)};var params={menu:"false",allowfullscreen:"true",allowScriptAccess:"always"};var attributes={};swfobject.embedSWF(vp.getPlayer()+"?sc="+now,tagetID,"100%","100%","9.0.0",vp.getFlashInstallURL(),flashvars,params,attributes);};api.video.createReportURL=function(nedstatSiteId,nedstatParamMap){var reportURL='http://int.sitestat.com/a-pi/'+nedstatSiteId+'/s?as3.nsPlayer'
for(var key in nedstatParamMap){reportURL+=encodeURIComponent('&'+key+"="+nedstatParamMap[key]);}
return reportURL;}
api.video.player=function(){this.videoPlayer=globalstaticurl+'common/flash/videoplayer/APIVideoPlayer2.swf';this.flashInstallURL=globalstaticurl+'common/flash/videoplayer/expressInstall.swf';this.videoPlayerId='apiVideoPlayer';this.videoPlayerHeight=442;this.videoPlayerWidth=512;};api.video.player.prototype.setPlayer=function(playerUrl){this.videoPlayer=playerUrl;};api.video.player.prototype.setFlashInstallURL=function(flashUrl){this.flashInstallURL=flashUrl;};api.video.player.prototype.setVideoPlayerId=function(v){this.videoPlayerId=v;};api.video.player.prototype.setVideoPlayerHeight=function(v){this.videoPlayerHeight=v;};api.video.player.prototype.setVideoPlayerWidth=function(v){this.videoPlayerWidth=v;};api.video.player.prototype.getPlayer=function(){return this.videoPlayer;};api.video.player.prototype.getFlashInstallURL=function(){return this.flashInstallURL;};api.video.player.prototype.getVideoPlayerId=function(){return this.videoPlayerId;};api.video.player.prototype.getVideoPlayerHeight=function(){return this.videoPlayerHeight;};api.video.player.prototype.getVideoPlayerWidth=function(){return this.videoPlayerWidth;};api.video.file=function(){this.videoTitle="";this.videoFile="";this.videoThumb="";this.autoplay=false;};api.video.file.prototype.setTitle=function(vTitle){this.videoTitle=escape(vTitle);};api.video.file.prototype.setFile=function(vFile){this.videoFile=vFile;};api.video.file.prototype.setThumb=function(vThumb){this.videoThumb=vThumb;};api.video.file.prototype.setDisplayTime=function(dTime){this.displayTime=dTime;};api.video.file.prototype.getPlaylist=function(){return'autoplay='+this.autoplay+'&playlist='+'<data><video>'+'<title>'+this.videoTitle+'</title>'+'<fileurl>'+this.videoFile+'</fileurl>'+'<thumburl>'+this.videoThumb+'</thumburl>'+'</video></data>';};api.poll=function(id,pubId,results,closed){this.form=document.forms[document.forms.length-1];this.returnGfx="/componada/resources/web/gfx/pix_fff.gif"
this.ajaxPrefix="/apiajax/";this.cookieName="apiPoll6";this.id=id;this.publicationId=pubId;this.results=results;this.closed=closed;this.fixResult=!(this.results.length>0);if(!api.polls[id])api.polls[id]=[this];else api.polls[id].push(this);this.checked=false;this.output=[];var opts=api.getElementsByClassName(this.form,"apiOption","div");for(var i=0;i<opts.length;i++){var percentDiv=api.bh("div",{cl:"apiResult"});opts[i].insertBefore(percentDiv,opts[i].firstChild);var barWrap=api.bh("div",{cl:"apiPollBarWrap"});;opts[i].appendChild(barWrap);var bar=api.bh("div",{cl:"apiPollBar"});;barWrap.appendChild(bar);this.output.push({per:percentDiv,bar:bar});if(this.fixResult)this.results.push(0);};this.chk();this.updateResults();if(this.closed)this.showResult();};api.poll.prototype.updateResults=function(){var This=this;var foo=new api.ajax({url:this.ajaxPrefix+this.id,onsuccess:function(req){This.updateCallback(req)}});foo.send();};api.poll.prototype.updateCallback=function(req){var result=JSON.parse(req.responseText);if(!!result.results){this.results=result.results;this.chk();}};api.poll.prototype.send=function(o){var ins=o.parentNode.parentNode.getElementsByTagName("input");var c=null;for(var i=0;i<ins.length;i++){if(ins[i].checked){c=ins[i].value;}};if(!c){return false;}
var coo=api.cookie.get(this.cookieName)||"|";coo+=this.id+":"+c+"|";api.cookie.set(this.cookieName,coo,30);var url='/do/test?mentometerId='+escape(this.id)+'&publicationId='+escape(this.publicationId)+'&redirectTo='+escape(this.returnGfx)+'&vote=svar'+escape(c);var image=new Image();image.src=url;this.showResult(c);};api.poll.prototype.chk=function(){var coo=api.cookie.get(this.cookieName)||"";var re=new RegExp("\\|"+this.id+"\\:(\\d+)\\|");if(re.test(coo)){this.showResult(RegExp.$1)}
else{var total=0;for(var i=0;i<this.results.length;i++){total+=this.results[i];}
api.getElementsByClassName(this.form,"apiCountTotal","span")[0].innerHTML=total;var This=this;api.getElementsByClassName(this.form,"apiPollSubmitBut","input")[0].onclick=function(){This.send(this)};}};api.poll.prototype.showResult=function(c){for(y=0;y<api.polls[this.id].length;y++){var cPoll=api.polls[this.id][y];var totout=api.getElementsByClassName(cPoll.form,"apiCountTotal","span")[0];var total=0;for(var i=0;i<cPoll.results.length;i++){if((i+1)==c)cPoll.results[i]++;total+=cPoll.results[i];};var ins=api.getElementsByClassName(cPoll.form,"apiPollOptIn","input");for(var i=0;i<ins.length;i++){if(c==ins[i].value){ins[i].checked="checked";};ins[i].disabled="disabled";var percent=(Math.round((cPoll.results[i]*1000)/total)/10);cPoll.output[i].per.innerHTML=percent+"%";cPoll.output[i].bar.style.width=percent+"%";};totout.innerHTML=total;cPoll.form.className="apiPollIsSubmited";if(this.closed)cPoll.form.className="apiPollIsClosed";cPoll.checked=true;};};api.polls=[];api.netmeeting=function(){};api.netmeeting.send=function(){document.getElementById("errorFieldTitle").innerHTML=''
document.getElementById("errorFieldBody").innerHTML=''
document.getElementById("errorFieldName").innerHTML=''
var title=document.getElementById("formTitle").value;var body=document.getElementById("formBody").value;var name=document.getElementById("formName").value;if(title==''||body==''||name==''){if(title==''){document.getElementById("errorFieldTitle").innerHTML=" - Tittel m&#229; fylles ut";}
if(body==''){document.getElementById("errorFieldBody").innerHTML=" - Sp&#248;rsm&#229;l m&#229; fylles ut";}
if(name==''){document.getElementById("errorFieldName").innerHTML=" - Navn m&#229; fylles ut";}
return false;}else{return true;}}
api.brokerguide_changeCounty=function(selectedChoice,defaultMunicipality,defaultDistrict,geographies){api.brokerguide_clearSelect($('#municipalities'),defaultMunicipality);api.brokerguide_clearSelect($('#districts'),defaultDistrict);if(selectedChoice!=''){$.each(geographies[selectedChoice]['municipalities'],function(index,value){$('#municipalities').append(api.brokerguide_createOptionHTML(value['name'],value['name']+" ("+value['count']+")"));});}
if($('#counties').children('option:selected').index()!=0){$('#municipalities').removeAttr('disabled');if($('#municipalities').children().size()==2){$('#municipalities').children('option:nth-child(2)').attr('selected','selected');api.brokerguide_changeMunicipality($('#municipalities').children('option:selected').val(),defaultDistrict,geographies);}
else{$('#districts').attr('disabled','disabled');}}
else{$('#municipalities').attr('disabled','disabled');$('#districts').attr('disabled','disabled');}}
api.brokerguide_changeMunicipality=function(selectedChoice,defaultDistrict,geographies){api.brokerguide_clearSelect($('#districts'),defaultDistrict);if(selectedChoice!=''){var municipalityEntry=api.brokerguide_getMuniciaplityEntry(selectedChoice,geographies[$('#counties').children('option:selected').val()]['municipalities'])
$.each(municipalityEntry['districts'],function(index,value){$('#districts').append(api.brokerguide_createOptionHTML(value['name'],value['name']+" ("+value['count']+")"));});}
if($('#municipalities').children('option:selected').index()!=0){$('#districts').removeAttr('disabled');if($('#districts').children().size()==2){$('#districts').children('option:nth-child(2)').attr('selected','selected');}}
else{$('#districts').attr('disabled','disabled');}}
api.brokerguide_clearSelect=function(selectObj,defaultLabel){selectObj.children().remove();selectObj.append(api.brokerguide_createOptionHTML("",defaultLabel));selectObj.children('option:first').attr('selected','selected');}
api.brokerguide_createOptionHTML=function(value,label){return'<option value="'+value+'">'+label+'</option>';}
api.brokerguide_getMuniciaplityEntry=function(name,municipalityList){var entry={};$.each(municipalityList,function(key,value){if(value['name']==name){entry=value;}});return entry}
function ns_onclick(a,url,name,type,e,winopt){if(e.button!=0){return false;}
var ctrlPressed=e.ctrlKey;var ns_l="http://int.sitestat.com/a-pi/"+nedstat_site+"/s?";ns_l+=name;ns_l+='&ns_type='+type+'&ns_action=view';ns_l+='&ns__t='+(new Date()).getTime();if(!url)url=a.href;var ns_0=document.referrer;if(ns_0.lastIndexOf('/')==ns_0.length-1)
ns_0=ns_0.substring(ns_0.lastIndexOf('/'),0);if(ns_0.length>0)
ns_l+='&amp;ns_referrer='+escape(ns_0);winopt=winopt||"";var target=(a&&a.target&&a.target!="")?(a.target.substring(0,1)=="_")?a.target.substring(1):a.target:"self";var ns_i=new Image();if(target=="self"&&ctrlPressed){}else{if(target&&url){if(window[target]){window.ns_softclick_timer=function(target,url){return function(){ns_i.onload=ns_i.onerror=function(){return;};window[((window[target])?target:"self")].location.href=url;}}(target,url);window.setTimeout('ns_softclick_timer()',5000);ns_i.onload=ns_i.onerror=window.ns_softclick_timer;}else{window.open(url,target,winopt);}}}
ns_i.src=ns_l;return false;}
function addNedstatOnclick(link,category){if(link.href){if(link.onmousedown!=null&&link.onmousedown.name=='nedstatPlaceholder'){return true;}
var clickType=(link.href.indexOf(nedstat_siteHost)>-1)?'clickin':'clickout';var counterName=calcCounterName(link,category,clickType);var old=(link.onmousedown)?link.onmousedown:function(){};var newFunc=function(event){old(event);ns_onclick(this,'',counterName,clickType,event);};newFunc.name="nedstatPlaceholder"
link.onmousedown=newFunc;}
return true;}
function calcCounterName(link,category,clickType){if(clickType=='clickout'){return category+'.'+link.hostname;}
return category;}
function onOrigoCreateObject(data_object){origoStatUrl=fullStatUrl+'&amp;ns_type=hidden&amp;origoComment=true'+'&amp;comment.created_by_id='+data_object.created_by_id+'&amp;comment.facebook_user='+data_object.facebook_user+'&amp;comment.body_char_count='+data_object.body_char_count+'&amp;comment.google_user='+data_object.google_user+'&amp;comment.object_id='+data_object.object_id+'&amp;comment.body_word_count='+data_object.body_word_count+'&amp;comment.role_signed_post='+data_object.role_signed_post+'&amp;comment.kudos_count='+data_object.kudos_count+'&amp;comment.sandbox_id='+data_object.sandbox_id+'&amp;comment.origo_user='+data_object.origo_user+'&amp;comment.created_at='+data_object.created_at;sitestat(origoStatUrl);}
var apiProspectFav=apiProspectFav||{};(function(){var publicationId,initialize,messageProperties;initialize=function(data){messageProperties=data;publicationId=data.publicationId;};apiProspectFav.favourite={activeFavourite:function activeFavourite(advertId){$('#apiFavourite'+advertId).addClass('active');$('#apiFavourite'+advertId).attr('title',messageProperties.remove);$('#apiFavourite'+advertId).text(messageProperties.remove);},inactiveFavourite:function inactiveFavourite(advertId){$('#apiFavourite'+advertId).removeClass('active');$('#apiFavourite'+advertId).attr('title',messageProperties.add);$('#apiFavourite'+advertId).text(messageProperties.add);},isFavourite:function isFavourite(advertId){return $('#apiFavourite'+advertId).hasClass('active');},init:function init(localJanus,janusUrl,useSSL,advertId){auth.init(localJanus,janusUrl,useSSL,publicationId);fav.initFavourite(publicationId,advertId,messageProperties.loginMessage,this.activeFavourite,this.inactiveFavourite,this.isFavourite);}};apiProspectFav.admin={initialize:initialize};}());api.streaming={};api.streaming.formatLiveVideoDate=function(date,fmt){function pad(value){return(value.toString().length<2)?'0'+value:value;}
return fmt.replace(/%([a-zA-Z])/g,function(_,fmtCode){switch(fmtCode){case'Y':return date.getUTCFullYear();case'M':return pad(date.getUTCMonth()+1);case'd':return pad(date.getUTCDate());case'H':return pad(date.getUTCHours());case'm':return pad(date.getUTCMinutes());case's':return pad(date.getUTCSeconds());default:throw new Error('Unsupported format code: '+fmtCode);}});}
api.streaming.showLiveNotification=function(divid,content,height){var div=document.getElementById(divid);div.innerHTML='<div style="width: 100%; height: 100%; text-align: center; line-height: '+height+'px; '+'background: #000; color: #FFF">'+content+'</div>';}
var api=api||{};api.classified={tipAFriend:function(_settings,_texts){var settings=_settings;var texts=_texts;function toggleButtons(){$('.tipAFriendButton').each(function(){if($(this).attr('disabled')){$(this).removeAttr('disabled');}
else{$(this).attr('disabled','disabled');}});}
function closePopup(){$(".dimbg").css("display","none");$("#apiTipFormSender, #apiTipFormEmailTo, #comment").val("");$(".apiValidationMessage").html("");$("#sendTipToFriend").css("display","none");fixBody();}
function tipAFriendDetectedSvg(){$('.tipAFriendButton').removeClass('tipAFriendButtonFallback');}
function tipAFriendDetectSvg(){var testImg='data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNzUiIGhlaWdodD0iMjc1Ij48L3N2Zz4%3D';var img=document.createElement('img');img.setAttribute('src',testImg);img.onload=tipAFriendDetectedSvg;}
function prospectTipAFriendConfirmation(message,statistics){$("#apiTipAFriendDiv").removeClass("apiTipAFriendWaiting");$("#apiTipAFriendDiv").removeClass("apiTipAFriendExpanded");$("#apiTipAFriendConfirmation").addClass("apiTipAFriendConfirmationExpanded");$(".apiTipAFriendSentMessage").html(message+statistics);closePopup();window.scrollTo(0,0);}
this.validate=function validate(){tipAFriendDetectSvg();$("#tipAFriendForm").validate({rules:{comment:{maxlength:settings.maxMsgLength}},groups:{tipAFriend:"recipient comment"},errorPlacement:function(error,element){$(".apiValidationMessage").html(error);},submitHandler:function(form){var recipient=document.getElementById("apiTipFormEmailTo").value;var action=form.action;var formData=$(form).serialize();$.ajax({type:'POST',url:action,data:formData,beforeSend:function(){$("#apiTipAFriendDiv").addClass("apiTipAFriendWaiting");toggleButtons();},success:function(data){if(data.errorMessage==""){prospectTipAFriendConfirmation(texts.message_sent+' '+recipient,texts.statistics);}else{$(".apiValidationMessage").html(texts.message_not_sent+': '+data.result);$("#apiTipAFriendDiv").removeClass("apiTipAFriendWaiting");}
toggleButtons();},error:function(request,status,exception){$("#apiTipAFriendDiv").removeClass("apiTipAFriendWaiting");$(".apiValidationMessage").html(texts.message_not_sent);toggleButtons();},timeout:20000,dataType:'json'});}});}}};api.FlowplayerVideo=function(id,playerURL,videoURL,previewURL,streamsenseURL,nedstatSiteId,nedstatParams,title,replayLabel,pubDate,showAds){var self=this;this.id=id;this.profilesPath='/API/muvi/v1/profile/';this.containerID='apiVideoContainer_'+id;this.playerURL=playerURL;this.videoURL=videoURL;this.previewURL=previewURL;this.streamsenseURL=streamsenseURL;this.replayLabel=replayLabel;this.videoTitle=title;this.nedstatLogUrl=this.createReportURL(nedstatSiteId,nedstatParams,title);this.bitrates=null;this.sections=this.getSections(document.URL);this.publicationName=this.getPubName(document.URL);this.pubDate=pubDate;this.flags=!!showAds?[]:['nocom'];var req=new XMLHttpRequest();req.open('GET',self.getProfilesUrl(self.videoURL));req.onreadystatechange=function(){if(req.readyState==4){if(req.status==200||req.status==304){self.bitrates=JSON.parse(req.responseText);}
self.insertPlayer();}};req.send();};api.FlowplayerVideo.prototype.isNocom=function(pubName){var nocoms=[];nocoms.push('frifagbevegelse');nocoms.push('aktuell');nocoms.push('fagbladet');nocoms.push('fontene');nocoms.push('hk-nytt');nocoms.push('loaktuelt');nocoms.push('magasinett');nocoms.push('nettverk1');nocoms.push('arbeidsmanden');for(var i=0;i<nocoms.length;i++){if(nocoms[i]==pubName){return true}}
return false;};api.FlowplayerVideo.prototype.getPubName=function(url){var parts=url.split('.');return parts[1];};api.FlowplayerVideo.prototype.getSections=function(url){var sections=url.split('/');sections.splice(0,3);sections.pop();return sections;};api.FlowplayerVideo.prototype.getProfilesUrl=function(videoURL){var parts=videoURL.split('/');var filename=parts[parts.length-1];return this.profilesPath+filename.split('.')[0]+'.json';};api.FlowplayerVideo.prototype.createReportURL=function(nedstatSiteId,nedstatParamMap,title){var reportURL='http://int.sitestat.com/amedia/mainsite/s?'+encodeURI(title);reportURL+=encodeURIComponent('&a_virtual='+nedstatSiteId);for(var key in nedstatParamMap){reportURL+=encodeURIComponent('&'+key+"="+nedstatParamMap[key]);}
return reportURL;};api.FlowplayerVideo.prototype.getProfileWithHighestBitrate=function(bitrates){var profileWithHighestBitrate=null;var profiles=(!!bitrates)?bitrates.profiles:null;if(profiles!=null){for(var i=0;i<profiles.length;i++){if(profileWithHighestBitrate==null||profiles[i].bitrate>profileWithHighestBitrate.bitrate){profileWithHighestBitrate=profiles[i];}}}
return profileWithHighestBitrate;}
api.FlowplayerVideo.prototype.getVideoURLToPlay=function(profile,baseVideoURL){var path=baseVideoURL.substring(0,baseVideoURL.lastIndexOf('/')+1);return(profile!=null)?path+profile.filename:baseVideoURL;}
api.FlowplayerVideo.prototype.insertPlayer=function(){var profile=this.getProfileWithHighestBitrate(this.bitrates);var videoURLToPlay=this.getVideoURLToPlay(profile,this.videoURL);flowplayer(this.containerID,{src:this.playerURL,wmode:'opaque'},{playlist:[{autoPlay:true,scaling:'fit',url:videoURLToPlay,vpflags:this.flags,ns_st_ty:'vod',ns_st_dt:this.pubDate,ns_st_pl:this.videoTitle,ns_st_pr:this.videoTitle,ns_st_ep:'1'}],play:{replayLabel:this.replayLabel},plugins:{videoplaza:{url:'http://service.cdn.videoplaza.tv/resources/flash/flowplayer-3.2.6/latest/vp_plugin.swf',vpDomain:'http://no-apdm.videoplaza.tv',vpTags:this.sections,vpShares:this.publicationName},streamsense:{url:this.streamsenseURL,logurl:this.nedstatLogUrl,debug:false,pageview:false}}}).qualityselector(this.id,this.bitrates,videoURLToPlay);};api.HtmlVideo=function htmlVideo(id,containerID,height,width,videoURL,previewURL,errorMsg){this.id=id;this.containerID=containerID;this.height=height;this.width=width;this.videoURL=videoURL;this.previewURL=previewURL;this.errorMsg=errorMsg;this.container=document.getElementById(containerID);this.insertPlayer();};api.HtmlVideo.prototype.insertPlayer=function(){var self=this;this.video=api.bh('video',{id:'video_'+this.id,width:this.width,height:this.height,controls:'controls',poster:this.previewURL});var source=api.bh('source',{src:this.videoURL,type:'video/mp4'});var noFlashMsg=api.bh('p',{ih:this.errorMsg});this.container.appendChild(this.video);this.video.appendChild(source);this.video.appendChild(noFlashMsg);source.addEventListener('error',function(){if(self.container.hasChildNodes()){self.container.removeChild(self.container.firstChild);}
self.container.innerHTML=self.errorMsg;});};api.HtmlVideo.prototype.doAdRequest=function doAdRequest(){var self=this;var vpConfig={vphost:'http://vp-validation.videoplaza.tv',src:self.videoURL,category:'validation',tags:['standard'],flags:[],playbackPosition:[]};var vpHost,contentMetadata,requestSettings,myPlayer,adTrack,adRequest,adDisplay,adSection,myPlayerSrc,myPlayerPoster,adResponse,playerState,ua,clickEvent;myPlayer=this.video;vpHost=(vpConfig.vphost)?vpConfig.vphost:"";ua=navigator.userAgent;clickEvent=(ua.match(/iPad/i))?"touchstart":"click";contentMetadata={category:(vpConfig.category)?vpConfig.category:"",tags:(vpConfig.tags)?vpConfig.tags:[],flags:(vpConfig.flags)?vpConfig.flags:[],contentForm:"shortForm",contentId:"",contentPartner:"",duration:(myPlayer.duration)?myPlayer.duration:0};requestSettings={height:myPlayer.height,width:myPlayer.width,playbackPosition:(vpConfig.playbackPosition)?vpConfig.playbackPosition:[],insertionPointType:"",maxBitRate:undefined};adRequest=({adCallModule:new videoplaza.core.AdCallModule(vpHost),newAdRequest:function(adtype){requestSettings.insertionPointType=adtype;this.adCallModule.requestAds(contentMetadata,requestSettings,this.onSuccess,this.onFail);},onFail:function(errorMessage){playerState.play();},onSuccess:function(ads){adResponse.filterAdsArr(ads);}});adResponse=({adsArr:[],filterAdsArr:function(ads){ads.forEach(function(ad,index,array){switch(ad.type)
{case'standard_spot':adResponse.adsArr.push(ad);break;case'inventory':adDisplay.inventory(ad);break;default:playerState.play();break;}});this.checkNumOfAvailableAds();},checkNumOfAvailableAds:function(){if(this.adsArr.length===0&&requestSettings.insertionPointType==='onBeforeContent'){playerState.play();}
else{adDisplay.standardSpot(this.adsArr[0]);}}});adDisplay=({adState:'',creative:null,currentAd:null,companionArr:[],standardSpot:function(ad){for(var i=ad.creatives.length-1;i>=0;i--){this.creative=ad.creatives[i];if(this.creative.id=='video')
this.currentAd=this.creative;else if(this.creative.type=='companion')
this.companionArr.push(this.creative);}
if(this.currentAd===null||this.currentAd.mediaFiles[0]===undefined){playerState.play();return;}
playerState.play({'src':this.currentAd.mediaFiles[0].uri,'controls':false,'poster':false});myPlayer.addEventListener(clickEvent,adDisplay.standardSpotClickThrough);adTrack.AD_IMPRESSION(ad);adTrack.AD_START();adTrack.AD_QUARTILES(ad.creatives[0].duration);},standardSpotClickThrough:function(){myPlayer.removeEventListener(clickEvent,adDisplay.standardSpotClickThrough);window.open(adDisplay.currentAd.clickThroughUri);adTrack.AD_CLICK_THROUGH();myPlayer.controls=true;myPlayer.pause();myPlayer.addEventListener(clickEvent,function onClickTogglePause(){this.removeEventListener(clickEvent,onClickTogglePause);myPlayer.play();},false);},inventory:function(ad){adTrack.AD_IMPRESSION(ad);}});adTrack=({tracker:new videoplaza.core.Tracker(),firstQuartile:0,midpoint:0,thirdQuartile:0,COMPANION_IMPRESSION:function(){this.tracker.track(adDisplay.currentAd,videoplaza.core.Tracker.trackingEvents.creative.creativeView);},AD_IMPRESSION:function(ad){this.tracker.track(ad,videoplaza.core.Tracker.trackingEvents.ad.impression);},AD_START:function(){this.tracker.track(adDisplay.currentAd,videoplaza.core.Tracker.trackingEvents.creative.start);},AD_COMPLETE:function(){this.tracker.track(adDisplay.currentAd,videoplaza.core.Tracker.trackingEvents.creative.complete);},AD_CLICK_THROUGH:function(){this.tracker.track(adDisplay.currentAd,videoplaza.core.Tracker.trackingEvents.creative.clickThrough);},AD_QUARTILES:function(duration){this.firstQuartile=Math.round((duration/100)*25);this.midpoint=Math.round((duration/100)*50);this.thirdQuartile=Math.round((duration/100)*75);myPlayer.addEventListener("timeupdate",adTrack.trackQuartiles);},trackQuartiles:function(){switch(Math.round(this.currentTime))
{case this.firstQuartile:this.tracker.track(adDisplay.currentAd,videoplaza.core.Tracker.trackingEvents.creative.firstQuartile);this.firstQuartile=NaN;return;case this.midpoint:this.tracker.track(adDisplay.currentAd,videoplaza.core.Tracker.trackingEvents.creative.midpoint);this.midpoint=NaN;return;case this.thirdQuartile:this.tracker.track(adDisplay.currentAd,videoplaza.core.Tracker.trackingEvents.creative.thirdQuartile);myPlayer.removeEventListener("timeupdate",adTrack.trackQuartiles);this.thirdQuartile=NaN;return;}}});adSection=({videoStart:function(type){myPlayer.pause();adRequest.newAdRequest('onBeforeContent');},videoCompleted:function(type){adResponse.adsArr.shift();if(adResponse.adsArr.length===0){myPlayer.removeEventListener(clickEvent,adDisplay.standardSpotClickThrough);myPlayer.src=self.videoURL;myPlayer.controls=true;myPlayer.play();}
else{adDisplay.standardSpot(adResponse.adsArr[0]);}}});playerState=({playerOriginalSrc:'',playerOriginalPoster:'',init:function(){myPlayerSrc=myPlayer.currentSrc;myPlayerPoster=myPlayer.poster;}(),play:function(config){if(!config){this.reset();}
else{myPlayer.src=(config.src)?config.src:myPlayerSrc;myPlayer.poster=(config.poster===false)?'':myPlayerPoster;myPlayer.controls=(config.controls!==undefined)?config.controls:true;myPlayer.addEventListener("timeupdate",function onTimeUpdate(){if(this.currentTime===this.duration){this.removeEventListener("timeupdate",onTimeUpdate);adSection.videoCompleted('onBeforeContent');}},false);}
myPlayer.addEventListener('loadstart',function playerPlay(){this.removeEventListener('loadstart',playerPlay);myPlayer.play();},false);},reset:function(){myPlayer.poster=myPlayerPoster;myPlayer.src=myPlayerSrc;myPlayer.controls=true;myPlayer.removeEventListener("click",adDisplay.standardSpotClickThrough);}});myPlayer.addEventListener("play",function videoStart(){this.removeEventListener('play',videoStart);adSection.videoStart('onBeforeContent');},false);if(!Array.prototype.forEach){Array.prototype.forEach=function(fun){if(typeof fun!="function")
throw new TypeError();for(var i=this.length-1;i>=0;i--){if(i in this)
fun.call(arguments[1],this[i],i,this);}};}};;(function LiveMatchCountdown(w){"use strict";var nifsUrl="http://nifs-cache.api.no/nifs/json/";function Countdown(params){for(var i in params){if(params.hasOwnProperty(i)){this[i]=params[i];}}
this.localTime=new Date(this.time);this.headerEl=api.bh("div",{cl:"top"});this.headerEl=api.bh("div",{cl:"top"});this.textEl=api.bh("div");this.statusEl=api.bh("span");this.timeEl=api.bh("span",{cl:"timeSpan"});this.linkEl=api.bh("a",{href:"/fotball/live/?kamp_id="+this["matchid"]});this.linkTvEl=api.bh("a",{href:"/tv",ih:this.messages["tvLinkText"]});this.textEl.appendChild(this.statusEl);this.textEl.appendChild(this.timeEl);this.el.appendChild(this.headerEl);this.el.appendChild(this.textEl);this.el.appendChild(this.linkEl);this.el.appendChild(api.bh("text"," "));this.el.appendChild(this.linkTvEl);this.setHeader();if(this.status=="after"){this.afterMatch();}else if(this.status=="before"){this.beforeMatch();}else{this.runningMatch();}}
Countdown.prototype={getMatch:function getMatch(){$.ajax({url:nifsUrl+"kamp.php?kamp_id="+this["matchid"]+"&sync="+(+new Date()),context:this,dataType:"json",success:function(d){this.title=d["hlag"]["navn"]+" "+(d["hlag"]["maal"]||0)+" - ";this.title+=(d["blag"]["maal"]||0)+" "+d["blag"]["navn"];this.setHeader();if(d&&d["hendelser"]&&d["hendelser"][0]&&d["hendelser"][0]["merknad"]){this.statusEl.innerHTML=d["hendelser"][0]["merknad"];}}});},afterMatch:function(){this.statusEl.innerHTML=this.messages["afterText"];this.linkEl.innerHTML=this.messages["afterLinkText"];},beforeMatch:function(){this.statusEl.innerHTML=this.messages["beforeText"];this.linkEl.innerHTML=this.messages["runningLinkText"];this.setTimeEl();},runningMatch:function(){this.statusEl.innerHTML=this.messages["runningText"];this.linkEl.innerHTML=this.messages["runningLinkText"];this.getMatch();},switchToRunning:function(){this.statusEl.innerHTML=this.messages["runningText"];this.timeEl.innerHTML="";this.getMatch();},timeLeft:function(){return Math.round((this.localTime-new Date())/1000);},setHeader:function(){this.headerEl.innerHTML="<h3>"+this.title+"</h3>";},setTimeEl:function(){var timeLeft=this.timeLeft(),newText="",days=0,hours=0,minutes=0,seconds=0,self=this;if(timeLeft<=0){this.switchToRunning();}else{days=Math.floor(timeLeft/(60*60*24));timeLeft%=(60*60*24);hours=Math.floor(timeLeft/(60*60));timeLeft%=(60*60);minutes=Math.floor(timeLeft/60);timeLeft%=(60);seconds=timeLeft;newText=days?' <strong>'+days+'</strong> '+
((days===1)?this.messages["day"]:this.messages["days"])+' ':'';newText+=(days||hours)?' <strong>'+hours+'</strong> '+
((hours===1)?this.messages["hour"]:this.messages["hours"])+' ':'';newText+=(days||hours||minutes)?' <strong>'+minutes+'</strong> '+
((minutes===1)?this.messages["minute"]:this.messages["minutes"])+' ':'';newText+=' <strong>'+seconds+'</strong> '+this.messages["seconds"];this.timeEl.innerHTML=newText;setTimeout(function(){self.setTimeEl()},970);}}};w.LiveMatchCountdown=Countdown;})(window);(function(definition){if(typeof define=="function"){define(definition);}else if(typeof YUI=="function"){YUI.add("es5",definition);}else{definition();}})(function(){function Empty(){}
if(!Function.prototype.bind){Function.prototype.bind=function bind(that){var target=this;if(typeof target!="function"){throw new TypeError("Function.prototype.bind called on incompatible "+target);}
var args=slice.call(arguments,1);var bound=function(){if(this instanceof bound){var result=target.apply(this,args.concat(slice.call(arguments)));if(Object(result)===result){return result;}
return this;}else{return target.apply(that,args.concat(slice.call(arguments)));}};if(target.prototype){Empty.prototype=target.prototype;bound.prototype=new Empty();Empty.prototype=null;}
return bound;};}
var call=Function.prototype.call;var prototypeOfArray=Array.prototype;var prototypeOfObject=Object.prototype;var slice=prototypeOfArray.slice;var _toString=call.bind(prototypeOfObject.toString);var owns=call.bind(prototypeOfObject.hasOwnProperty);var defineGetter;var defineSetter;var lookupGetter;var lookupSetter;var supportsAccessors;if((supportsAccessors=owns(prototypeOfObject,"__defineGetter__"))){defineGetter=call.bind(prototypeOfObject.__defineGetter__);defineSetter=call.bind(prototypeOfObject.__defineSetter__);lookupGetter=call.bind(prototypeOfObject.__lookupGetter__);lookupSetter=call.bind(prototypeOfObject.__lookupSetter__);}
if([1,2].splice(0).length!=2){var array_splice=Array.prototype.splice;Array.prototype.splice=function(start,deleteCount){if(!arguments.length){return[];}else{return array_splice.apply(this,[start===void 0?0:start,deleteCount===void 0?(this.length-start):deleteCount].concat(slice.call(arguments,2)))}};}
if([].unshift(0)!=1){var array_unshift=Array.prototype.unshift;Array.prototype.unshift=function(){array_unshift.apply(this,arguments);return this.length;};}
if(!Array.isArray){Array.isArray=function isArray(obj){return _toString(obj)=="[object Array]";};}
var boxedString=Object("a"),splitString=boxedString[0]!="a"||!(0 in boxedString);if(!Array.prototype.forEach){Array.prototype.forEach=function forEach(fun){var object=toObject(this),self=splitString&&_toString(this)=="[object String]"?this.split(""):object,thisp=arguments[1],i=-1,length=self.length>>>0;if(_toString(fun)!="[object Function]"){throw new TypeError();}
while(++i<length){if(i in self){fun.call(thisp,self[i],i,object);}}};}
if(!Array.prototype.map){Array.prototype.map=function map(fun){var object=toObject(this),self=splitString&&_toString(this)=="[object String]"?this.split(""):object,length=self.length>>>0,result=Array(length),thisp=arguments[1];if(_toString(fun)!="[object Function]"){throw new TypeError(fun+" is not a function");}
for(var i=0;i<length;i++){if(i in self)
result[i]=fun.call(thisp,self[i],i,object);}
return result;};}
if(!Array.prototype.filter){Array.prototype.filter=function filter(fun){var object=toObject(this),self=splitString&&_toString(this)=="[object String]"?this.split(""):object,length=self.length>>>0,result=[],value,thisp=arguments[1];if(_toString(fun)!="[object Function]"){throw new TypeError(fun+" is not a function");}
for(var i=0;i<length;i++){if(i in self){value=self[i];if(fun.call(thisp,value,i,object)){result.push(value);}}}
return result;};}
if(!Array.prototype.every){Array.prototype.every=function every(fun){var object=toObject(this),self=splitString&&_toString(this)=="[object String]"?this.split(""):object,length=self.length>>>0,thisp=arguments[1];if(_toString(fun)!="[object Function]"){throw new TypeError(fun+" is not a function");}
for(var i=0;i<length;i++){if(i in self&&!fun.call(thisp,self[i],i,object)){return false;}}
return true;};}
if(!Array.prototype.some){Array.prototype.some=function some(fun){var object=toObject(this),self=splitString&&_toString(this)=="[object String]"?this.split(""):object,length=self.length>>>0,thisp=arguments[1];if(_toString(fun)!="[object Function]"){throw new TypeError(fun+" is not a function");}
for(var i=0;i<length;i++){if(i in self&&fun.call(thisp,self[i],i,object)){return true;}}
return false;};}
if(!Array.prototype.reduce){Array.prototype.reduce=function reduce(fun){var object=toObject(this),self=splitString&&_toString(this)=="[object String]"?this.split(""):object,length=self.length>>>0;if(_toString(fun)!="[object Function]"){throw new TypeError(fun+" is not a function");}
if(!length&&arguments.length==1){throw new TypeError("reduce of empty array with no initial value");}
var i=0;var result;if(arguments.length>=2){result=arguments[1];}else{do{if(i in self){result=self[i++];break;}
if(++i>=length){throw new TypeError("reduce of empty array with no initial value");}}while(true);}
for(;i<length;i++){if(i in self){result=fun.call(void 0,result,self[i],i,object);}}
return result;};}
if(!Array.prototype.reduceRight){Array.prototype.reduceRight=function reduceRight(fun){var object=toObject(this),self=splitString&&_toString(this)=="[object String]"?this.split(""):object,length=self.length>>>0;if(_toString(fun)!="[object Function]"){throw new TypeError(fun+" is not a function");}
if(!length&&arguments.length==1){throw new TypeError("reduceRight of empty array with no initial value");}
var result,i=length-1;if(arguments.length>=2){result=arguments[1];}else{do{if(i in self){result=self[i--];break;}
if(--i<0){throw new TypeError("reduceRight of empty array with no initial value");}}while(true);}
do{if(i in this){result=fun.call(void 0,result,self[i],i,object);}}while(i--);return result;};}
if(!Array.prototype.indexOf||([0,1].indexOf(1,2)!=-1)){Array.prototype.indexOf=function indexOf(sought){var self=splitString&&_toString(this)=="[object String]"?this.split(""):toObject(this),length=self.length>>>0;if(!length){return-1;}
var i=0;if(arguments.length>1){i=toInteger(arguments[1]);}
i=i>=0?i:Math.max(0,length+i);for(;i<length;i++){if(i in self&&self[i]===sought){return i;}}
return-1;};}
if(!Array.prototype.lastIndexOf||([0,1].lastIndexOf(0,-3)!=-1)){Array.prototype.lastIndexOf=function lastIndexOf(sought){var self=splitString&&_toString(this)=="[object String]"?this.split(""):toObject(this),length=self.length>>>0;if(!length){return-1;}
var i=length-1;if(arguments.length>1){i=Math.min(i,toInteger(arguments[1]));}
i=i>=0?i:length-Math.abs(i);for(;i>=0;i--){if(i in self&&sought===self[i]){return i;}}
return-1;};}
if(!Object.keys){var hasDontEnumBug=true,dontEnums=["toString","toLocaleString","valueOf","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","constructor"],dontEnumsLength=dontEnums.length;for(var key in{"toString":null}){hasDontEnumBug=false;}
Object.keys=function keys(object){if((typeof object!="object"&&typeof object!="function")||object===null){throw new TypeError("Object.keys called on a non-object");}
var keys=[];for(var name in object){if(owns(object,name)){keys.push(name);}}
if(hasDontEnumBug){for(var i=0,ii=dontEnumsLength;i<ii;i++){var dontEnum=dontEnums[i];if(owns(object,dontEnum)){keys.push(dontEnum);}}}
return keys;};}
var negativeDate=-62198755200000,negativeYearString="-000001";if(!Date.prototype.toISOString||(new Date(negativeDate).toISOString().indexOf(negativeYearString)===-1)){Date.prototype.toISOString=function toISOString(){var result,length,value,year,month;if(!isFinite(this)){throw new RangeError("Date.prototype.toISOString called on non-finite value.");}
year=this.getUTCFullYear();month=this.getUTCMonth();year+=Math.floor(month/12);month=(month%12+12)%12;result=[month+1,this.getUTCDate(),this.getUTCHours(),this.getUTCMinutes(),this.getUTCSeconds()];year=((year<0?"-":(year>9999?"+":""))+
("00000"+Math.abs(year)).slice(0<=year&&year<=9999?-4:-6));length=result.length;while(length--){value=result[length];if(value<10){result[length]="0"+value;}}
return(year+"-"+result.slice(0,2).join("-")+"T"+result.slice(2).join(":")+"."+
("000"+this.getUTCMilliseconds()).slice(-3)+"Z");};}
var dateToJSONIsSupported=false;try{dateToJSONIsSupported=(Date.prototype.toJSON&&new Date(NaN).toJSON()===null&&new Date(negativeDate).toJSON().indexOf(negativeYearString)!==-1&&Date.prototype.toJSON.call({toISOString:function(){return true;}}));}catch(e){}
if(!dateToJSONIsSupported){Date.prototype.toJSON=function toJSON(key){var o=Object(this),tv=toPrimitive(o),toISO;if(typeof tv==="number"&&!isFinite(tv)){return null;}
toISO=o.toISOString;if(typeof toISO!="function"){throw new TypeError("toISOString property is not callable");}
return toISO.call(o);};}
if(!Date.parse||"Date.parse is buggy"){Date=(function(NativeDate){function Date(Y,M,D,h,m,s,ms){var length=arguments.length;if(this instanceof NativeDate){var date=length==1&&String(Y)===Y?new NativeDate(Date.parse(Y)):length>=7?new NativeDate(Y,M,D,h,m,s,ms):length>=6?new NativeDate(Y,M,D,h,m,s):length>=5?new NativeDate(Y,M,D,h,m):length>=4?new NativeDate(Y,M,D,h):length>=3?new NativeDate(Y,M,D):length>=2?new NativeDate(Y,M):length>=1?new NativeDate(Y):new NativeDate();date.constructor=Date;return date;}
return NativeDate.apply(this,arguments);};var isoDateExpression=new RegExp("^"+"(\\d{4}|[\+\-]\\d{6})"+"(?:-(\\d{2})"+"(?:-(\\d{2})"+"(?:"+"T(\\d{2})"+":(\\d{2})"+"(?:"+":(\\d{2})"+"(?:\\.(\\d{3}))?"+")?"+"("+"Z|"+"(?:"+"([-+])"+"(\\d{2})"+":(\\d{2})"+")"+")?)?)?)?"+"$");var months=[0,31,59,90,120,151,181,212,243,273,304,334,365];function dayFromMonth(year,month){var t=month>1?1:0;return(months[month]+
Math.floor((year-1969+t)/4)-
Math.floor((year-1901+t)/100)+
Math.floor((year-1601+t)/400)+
365*(year-1970));}
for(var key in NativeDate){Date[key]=NativeDate[key];}
Date.now=NativeDate.now;Date.UTC=NativeDate.UTC;Date.prototype=NativeDate.prototype;Date.prototype.constructor=Date;Date.parse=function parse(string){var match=isoDateExpression.exec(string);if(match){var year=Number(match[1]),month=Number(match[2]||1)-1,day=Number(match[3]||1)-1,hour=Number(match[4]||0),minute=Number(match[5]||0),second=Number(match[6]||0),millisecond=Number(match[7]||0),offset=!match[4]||match[8]?0:Number(new NativeDate(1970,0)),signOffset=match[9]==="-"?1:-1,hourOffset=Number(match[10]||0),minuteOffset=Number(match[11]||0),result;if(hour<(minute>0||second>0||millisecond>0?24:25)&&minute<60&&second<60&&millisecond<1000&&month>-1&&month<12&&hourOffset<24&&minuteOffset<60&&day>-1&&day<(dayFromMonth(year,month+1)-
dayFromMonth(year,month))){result=((dayFromMonth(year,month)+day)*24+
hour+
hourOffset*signOffset)*60;result=((result+minute+minuteOffset*signOffset)*60+
second)*1000+millisecond+offset;if(-8.64e15<=result&&result<=8.64e15){return result;}}
return NaN;}
return NativeDate.parse.apply(this,arguments);};return Date;})(Date);}
if(!Date.now){Date.now=function now(){return new Date().getTime();};}
if("0".split(void 0,0).length){var string_split=String.prototype.split;String.prototype.split=function(separator,limit){if(separator===void 0&&limit===0)return[];return string_split.apply(this,arguments);}}
if("".substr&&"0b".substr(-1)!=="b"){var string_substr=String.prototype.substr;String.prototype.substr=function(start,length){return string_substr.call(this,start<0?((start=this.length+start)<0?0:start):start,length);}}
var ws="\x09\x0A\x0B\x0C\x0D\x20\xA0\u1680\u180E\u2000\u2001\u2002\u2003"+"\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u202F\u205F\u3000\u2028"+"\u2029\uFEFF";if(!String.prototype.trim||ws.trim()){ws="["+ws+"]";var trimBeginRegexp=new RegExp("^"+ws+ws+"*"),trimEndRegexp=new RegExp(ws+ws+"*$");String.prototype.trim=function trim(){if(this===undefined||this===null){throw new TypeError("can't convert "+this+" to object");}
return String(this).replace(trimBeginRegexp,"").replace(trimEndRegexp,"");};}
function toInteger(n){n=+n;if(n!==n){n=0;}else if(n!==0&&n!==(1/0)&&n!==-(1/0)){n=(n>0||-1)*Math.floor(Math.abs(n));}
return n;}
function isPrimitive(input){var type=typeof input;return(input===null||type==="undefined"||type==="boolean"||type==="number"||type==="string");}
function toPrimitive(input){var val,valueOf,toString;if(isPrimitive(input)){return input;}
valueOf=input.valueOf;if(typeof valueOf==="function"){val=valueOf.call(input);if(isPrimitive(val)){return val;}}
toString=input.toString;if(typeof toString==="function"){val=toString.call(input);if(isPrimitive(val)){return val;}}
throw new TypeError();}
var toObject=function(o){if(o==null){throw new TypeError("can't convert "+o+" to object");}
return Object(o);};});(function(){if(typeof window.Element==="undefined"||"classList"in document.documentElement)return;var prototype=Array.prototype,indexOf=prototype.indexOf,slice=prototype.slice,push=prototype.push,splice=prototype.splice,join=prototype.join;function DOMTokenList(el){this._element=el;if(el.className!=this._classCache){this._classCache=el.className;if(!this._classCache)return;var classes=this._classCache.replace(/^\s+|\s+$/g,'').split(/\s+/),i;for(i=0;i<classes.length;i++){push.call(this,classes[i]);}}};function setToClassName(el,classes){el.className=classes.join(' ');}
DOMTokenList.prototype={add:function(token){if(this.contains(token))return;push.call(this,token);setToClassName(this._element,slice.call(this,0));},contains:function(token){return indexOf.call(this,token)!==-1;},item:function(index){return this[index]||null;},remove:function(token){var i=indexOf.call(this,token);if(i===-1){return;}
splice.call(this,i,1);setToClassName(this._element,slice.call(this,0));},toString:function(){return join.call(this,' ');},toggle:function(token){if(!this.contains(token)){this.add(token);}else{this.remove(token);}
return this.contains(token);}};window.DOMTokenList=DOMTokenList;function defineElementGetter(obj,prop,getter){if(Object.defineProperty){Object.defineProperty(obj,prop,{get:getter})}else{obj.__defineGetter__(prop,getter);}}
defineElementGetter(Element.prototype,'classList',function(){return new DOMTokenList(this);});})();;(function(window,document){var version='3.6.2pre';var options=window.html5||{};var reSkip=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i;var saveClones=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i;var supportsHtml5Styles;var expando='_html5shiv';var expanID=0;var expandoData={};var supportsUnknownElements;(function(){try{var a=document.createElement('a');a.innerHTML='<xyz></xyz>';supportsHtml5Styles=('hidden'in a);supportsUnknownElements=a.childNodes.length==1||(function(){(document.createElement)('a');var frag=document.createDocumentFragment();return(typeof frag.cloneNode=='undefined'||typeof frag.createDocumentFragment=='undefined'||typeof frag.createElement=='undefined');}());}catch(e){supportsHtml5Styles=true;supportsUnknownElements=true;}}());function addStyleSheet(ownerDocument,cssText){var p=ownerDocument.createElement('p'),parent=ownerDocument.getElementsByTagName('head')[0]||ownerDocument.documentElement;p.innerHTML='x<style>'+cssText+'</style>';return parent.insertBefore(p.lastChild,parent.firstChild);}
function getElements(){var elements=html5.elements;return typeof elements=='string'?elements.split(' '):elements;}
function getExpandoData(ownerDocument){var data=expandoData[ownerDocument[expando]];if(!data){data={};expanID++;ownerDocument[expando]=expanID;expandoData[expanID]=data;}
return data;}
function createElement(nodeName,ownerDocument,data){if(!ownerDocument){ownerDocument=document;}
if(supportsUnknownElements){return ownerDocument.createElement(nodeName);}
if(!data){data=getExpandoData(ownerDocument);}
var node;if(data.cache[nodeName]){node=data.cache[nodeName].cloneNode();}else if(saveClones.test(nodeName)){node=(data.cache[nodeName]=data.createElem(nodeName)).cloneNode();}else{node=data.createElem(nodeName);}
return node.canHaveChildren&&!reSkip.test(nodeName)?data.frag.appendChild(node):node;}
function createDocumentFragment(ownerDocument,data){if(!ownerDocument){ownerDocument=document;}
if(supportsUnknownElements){return ownerDocument.createDocumentFragment();}
data=data||getExpandoData(ownerDocument);var clone=data.frag.cloneNode(),i=0,elems=getElements(),l=elems.length;for(;i<l;i++){clone.createElement(elems[i]);}
return clone;}
function shivMethods(ownerDocument,data){if(!data.cache){data.cache={};data.createElem=ownerDocument.createElement;data.createFrag=ownerDocument.createDocumentFragment;data.frag=data.createFrag();}
ownerDocument.createElement=function(nodeName){if(!html5.shivMethods){return data.createElem(nodeName);}
return createElement(nodeName,ownerDocument,data);};ownerDocument.createDocumentFragment=Function('h,f','return function(){'+'var n=f.cloneNode(),c=n.createElement;'+'h.shivMethods&&('+
getElements().join().replace(/\w+/g,function(nodeName){data.createElem(nodeName);data.frag.createElement(nodeName);return'c("'+nodeName+'")';})+');return n}')(html5,data.frag);}
function shivDocument(ownerDocument){if(!ownerDocument){ownerDocument=document;}
var data=getExpandoData(ownerDocument);if(html5.shivCSS&&!supportsHtml5Styles&&!data.hasCSS){data.hasCSS=!!addStyleSheet(ownerDocument,'article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}'+'mark{background:#FF0;color:#000}');}
if(!supportsUnknownElements){shivMethods(ownerDocument,data);}
return ownerDocument;}
var html5={'elements':options.elements||'abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup main mark meter nav output progress section summary time video','version':version,'shivCSS':(options.shivCSS!==false),'supportsUnknownElements':supportsUnknownElements,'shivMethods':(options.shivMethods!==false),'type':'default','shivDocument':shivDocument,createElement:createElement,createDocumentFragment:createDocumentFragment};window.html5=html5;shivDocument(document);}(this,document));